config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "home/index"
  resources :prizes
  resources :tickets
  resources :raffles
  resources :kinds
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kind.rb
class Kind < ApplicationRecord
  validates_presence_of :description
  validates_presence_of :initial
  validates_presence_of :step
  validates_presence_of :quantity

  def to_s
    description
  end
end

app/models/prize.rb
class Prize < ApplicationRecord
  validates_presence_of :description
  validates_presence_of :placing
  belongs_to :raffle
  belongs_to :ticket, optional: true
end

app/models/raffle.rb
class Raffle < ApplicationRecord
  validates_presence_of :title
  validates_presence_of :probable_draw_at
  validates_presence_of :start_sale_at
  validates_presence_of :finishes_sale_at
  validates_presence_of :ticket_value
  belongs_to :user
  belongs_to :kind
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  validates_presence_of :number
  belongs_to :user, optional: true
  belongs_to :raffle
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :password
  # validates_presence_of :admin
  has_many:raffles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/kinds_controller.rb
class KindsController < ApplicationController
  before_action :set_kind, only: [:show, :edit, :update, :destroy]

  # GET /kinds
  def index
    @kinds = Kind.all
  end

  # GET /kinds/1
  def show
  end

  # GET /kinds/new
  def new
    @kind = Kind.new
  end

  # GET /kinds/1/edit
  def edit
  end

  # POST /kinds
  def create
    @kind = Kind.new(kind_params)

    if @kind.save
      redirect_to @kind, notice: 'Kind was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /kinds/1
  def update
    if @kind.update(kind_params)
      redirect_to @kind, notice: 'Kind was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /kinds/1
  def destroy
    @kind.destroy
    redirect_to kinds_url, notice: 'Kind was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kind
      @kind = Kind.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def kind_params
      params.require(:kind).permit(:description, :initial, :step, :quantity)
    end
end

app/controllers/prizes_controller.rb
class PrizesController < ApplicationController
  before_action :set_prize, only: [:show, :edit, :update, :destroy]

  # GET /prizes
  def index
    @prizes = Prize.all
  end

  # GET /prizes/1
  def show
  end

  # GET /prizes/new
  def new
    @prize = Prize.new
  end

  # GET /prizes/1/edit
  def edit
  end

  # POST /prizes
  def create
    @prize = Prize.new(prize_params)

    if @prize.save
      redirect_to @prize, notice: 'Prize was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /prizes/1
  def update
    if @prize.update(prize_params)
      redirect_to @prize, notice: 'Prize was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /prizes/1
  def destroy
    @prize.destroy
    redirect_to prizes_url, notice: 'Prize was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prize
      @prize = Prize.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def prize_params
      params.require(:prize).permit(:description, :placing, :raffle_id, :ticket_id)
    end
end

app/controllers/raffles_controller.rb
class RafflesController < ApplicationController
  before_action :set_raffle, only: [:show, :edit, :update, :destroy]
  # skip_before_action :authenticate_user!, [:new, :create]

  # GET /raffles
  def index
    @raffles = Raffle.all
    # @raffles = current_user.raffles

  end

  # GET /raffles/1
  def show
  end

  # GET /raffles/new
  def new
    @raffle = Raffle.new()
  end

  # GET /raffles/1/edit
  def edit
  end

  # POST /raffles
  def create
    @raffle = Raffle.new(raffle_params)
    @raffle.user = current_user

    if @raffle.save
      redirect_to @raffle, notice: "Raffle was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /raffles/1
  def update
    if @raffle.update(raffle_params)
      redirect_to @raffle, notice: "Raffle was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /raffles/1
  def destroy
    @raffle.destroy
    redirect_to raffles_url, notice: "Raffle was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_raffle
    @raffle = Raffle.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def raffle_params
    params.require(:raffle).permit(:title, :description, :probable_draw_at, :start_sale_at, :finishes_sale_at, :ticket_value, :kind_id)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
    @ticket.user = current_user
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  def create
    @ticket = Ticket.new(ticket_params)

    if @ticket.save
      redirect_to @ticket, notice: "Ticket was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /tickets/1
  def update
    if @ticket.update(ticket_params)
      redirect_to @ticket, notice: "Ticket was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /tickets/1
  def destroy
    @ticket.destroy
    redirect_to tickets_url, notice: "Ticket was successfully destroyed."
  end

  # def to_s
  #   number
  # end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def ticket_params
    params.require(:ticket).permit(:number, :raffle_id, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: "User was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: "User was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: "User was successfully destroyed."
  end


  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email, :password, :photo, :root)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/prizes_helper.rb
module PrizesHelper
end

app/helpers/raffles_helper.rb
module RafflesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<% content_for :title do %>
  Kinds
<% end %>

<div class="page-header">

<%= link_to raffles_path, class: 'btn btn-info btn-sm' do %>
              <%= icon 'fas', 'eye', class: 'fa-fw' %>
            View Raffles
<% end %>
</div>

app/views/kinds/_form.html.erb
<%= simple_form_for @kind do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :description %>
    <%= f.input :initial %>
    <%= f.input :step %>
    <%= f.input :quantity %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, f.object.new_record? ? 'Create Kind' : 'Update Kind', class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>

app/views/kinds/edit.html.erb
<% content_for :title do %>
  Kind editing
<% end %>

<div class="page-header">
  <h1>Kind editing</h1>
  <div>
    <%= link_to @kind, class: 'btn btn-info' do %>
      <%= icon 'fas', 'eye' %>
      View
    <% end %>
    <%= link_to kinds_path, class: 'btn btn-outline-secondary' do %>
      <%= icon 'fas', 'bars' %>
      Back
    <% end %>
  </div>
</div>

<%= render 'form' %>

app/views/kinds/index.html.erb
<% content_for :title do %>
  Kinds
<% end %>

<div class="page-header">
  <h1>Kinds</h1>
  <%= link_to new_kind_path, class: 'btn btn-primary' do %>
    <%= icon 'fas', 'plus' %>
    New Kind
  <% end %>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Description</th>
        <th>Initial</th>
        <th>Step</th>
        <th>Quantity</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @kinds.each do |kind| %>
        <tr>
          <td><%= kind.description %></td>
          <td><%= kind.initial %></td>
          <td><%= kind.step %></td>
          <td><%= kind.quantity %></td>
          <td>
            <%= link_to kind, class: 'btn btn-info btn-sm' do %>
              <%= icon 'fas', 'eye', class: 'fa-fw' %>
            <% end %>
            <%= link_to edit_kind_path(kind), class: 'btn btn-success btn-sm' do %>
              <%= icon 'fas', 'edit', class: 'fa-fw' %>
            <% end %>
            <%= link_to kind, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' do %>
              <%= icon 'fas', 'times', class: 'fa-fw' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/kinds/new.html.erb
<% content_for :title do %>
  New Kind
<% end %>

<div class="page-header">
  <h1>New Kind</h1>
  <%= link_to kinds_path, class: 'btn btn-outline-secondary' do %>
    <%= icon 'fas', 'bars' %>
    Back
  <% end %>
</div>

<%= render 'form' %>

app/views/kinds/show.html.erb
<% content_for :title do %>
  Kind's details
<% end %>

<div class="page-header">
  <h1>Kind's details</h1>
  <div>
    <%= link_to edit_kind_path(@kind), class: 'btn btn-success' do %>
      <%= icon 'fas', 'edit' %>
      Edit
    <% end %>
    <%= link_to kinds_path, class: 'btn btn-outline-secondary' do %>
      <%= icon 'fas', 'bars' %>
      Back
    <% end %>
  </div>
</div>

<dl class="dl-horizontal">
  <dt>Description:</dt>
  <dd><%= @kind.description %></dd>

  <dt>Initial:</dt>
  <dd><%= @kind.initial %></dd>

  <dt>Step:</dt>
  <dd><%= @kind.step %></dd>

  <dt>Quantity:</dt>
  <dd><%= @kind.quantity %></dd>

</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) + ' | ' : '' %>RaffleManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
      <div class="container">
        <%= link_to 'Home', home_index_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <% if user_signed_in? %>       
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <%= link_to 'Kinds', kinds_path, class: 'nav-link'%> 
              </li>             
            </ul>
          </div>
        <%end%>  


        <p class="navbar-text float-right">
          <% if user_signed_in? %>
            <strong><%= current_user.name %></strong> |
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
          <% else %>
            <%= link_to "Register", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </div>

    </nav>



    
    <div class="container">
      <% if notice %>
        <div class="alert alert-success"><%= notice %></div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger"><%= alert %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/prizes/_form.html.erb
<%= simple_form_for @prize do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :description %>
    <%= f.input :placing %>
    <%= f.association :raffle %>
    <%= f.association :ticket%>
  </div>

  <div class="form-actions">
    <%= f.button :submit, f.object.new_record? ? 'Create Prize' : 'Update Prize', class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>

app/views/prizes/edit.html.erb
<% content_for :title do %>
  Prize editing
<% end %>

<div class="page-header">
  <h1>Prize editing</h1>
  <div>
    <%= link_to @prize, class: 'btn btn-info' do %>
      <%= icon 'fas', 'eye' %>
      View
    <% end %>
    <%= link_to prizes_path, class: 'btn btn-outline-secondary' do %>
      <%= icon 'fas', 'bars' %>
      Back
    <% end %>
  </div>
</div>

<%= render 'form' %>

app/views/prizes/new.html.erb
<% content_for :title do %>
  New Prize
<% end %>

<div class="page-header">
  <h1>New Prize</h1>
  <%= link_to prizes_path, class: 'btn btn-outline-secondary' do %>
    <%= icon 'fas', 'bars' %>
    Back
  <% end %>
</div>

<%= render 'form' %>

app/views/prizes/show.html.erb
<% content_for :title do %>
  Prize's details
<% end %>

<div class="page-header">
  <h1>Prize's details</h1>
  <div>
    <%= link_to edit_prize_path(@prize), class: 'btn btn-success' do %>
      <%= icon 'fas', 'edit' %>
      Editar
    <% end %>
    <%= link_to prizes_path, class: 'btn btn-outline-secondary' do %>
      <%= icon 'fas', 'bars' %>
      Back
    <% end %>
  </div>
</div>

<dl class="dl-horizontal">
  <dt>Description:</dt>
  <dd><%= @prize.description %></dd>

  <dt>Placing:</dt>
  <dd><%= @prize.placing %></dd>

  <dt>Raffle:</dt>
  <dd><%= @prize.raffle.title %></dd>

  <dt>Ticket:</dt>
  <dd><%= @prize.ticket.number %></dd>

</dl>

app/views/raffles/edit.html.erb
<% content_for :title do %>
  Editing Raffle
<% end %>

<div class="page-header">
  <h1>Editing Raffle</h1>
  <div>
    <%= link_to @raffle, class: 'btn btn-info' do %>
      <%= icon 'fas', 'eye' %>
      View
    <% end %>
    <%= link_to raffles_path, class: 'btn btn-outline-secondary' do %>
      <%= icon 'fas', 'bars' %>
      Back
    <% end %>
  </div>
</div>

<%= render 'form' %>

app/views/raffles/index.html.erb
<% content_for :title do %>
  Raffles
<% end %>

<div class="page-header">
  <h1>Raffles</h1>
  
  <%= link_to new_raffle_path, class: 'btn btn-primary' do %>
    <%= icon 'fas', 'plus' %>
    Create Raffle
  <% end %>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover table-bg-scale: -80%">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Probable draw at</th>
        <th>Start sale at</th>
        <th>Finishes sale at</th>
        <th>Drawn at</th>
        <th>Ticket value</th>
        <th>User</th>
        <th>Kind</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @raffles.each do |raffle| %>
        <tr>
          <td><%= raffle.title %></td>
          <td><%= raffle.description %></td>
          <td><%= raffle.probable_draw_at.strftime("%FT%T") %></td>
          <td><%= raffle.start_sale_at.strftime("%FT%T") %></td>
          <td><%= raffle.finishes_sale_at.strftime("%FT%T") %></td>
          <td><%= raffle.drawn_at %></td>
          <td><%= raffle.ticket_value %></td>
          <td><%= raffle.user.name %></td>
          <td><%= raffle.kind %></td>
          <td>
            <%= link_to raffle, class: 'btn btn-info btn-sm' do %>
              <%= icon 'fas', 'eye', class: 'fa-fw' %>
            <% end %>
            <%= link_to edit_raffle_path(raffle), class: 'btn btn-success btn-sm' do %>
              <%= icon 'fas', 'edit', class: 'fa-fw' %>
            <% end %>
            <%= link_to raffle, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' do %>
              <%= icon 'fas', 'times', class: 'fa-fw' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/raffles/new.html.erb
<% content_for :title do %>
  New Raffle
<% end %>

<div class="page-header">
  <h1>New Raffle</h1>
  <%= link_to raffles_path, class: 'btn btn-outline-secondary' do %>
    <%= icon 'fas', 'bars' %>
    Back
  <% end %>
</div>

<%= render 'form' %>

app/views/raffles/show.html.erb
<% content_for :title do %>
  Raffle's details
<% end %>

<div class="page-header">
  <h1>Raffle's details</h1>
  <div>
    <%= link_to edit_raffle_path(@raffle), class: 'btn btn-success' do %>
      <%= icon 'fas', 'edit' %>
      Edit
    <% end %>
    <%= link_to raffles_path, class: 'btn btn-outline-secondary' do %>
      <%= icon 'fas', 'bars' %>
      Back
    <% end %>
  </div>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @raffle.title %></dd>

  <dt>Description:</dt>
  <dd><%= @raffle.description %></dd>

  <dt>Probable draw at:</dt>
  <dd><%= @raffle.probable_draw_at, format: "%d de %B de %Y" %></dd>

  <dt>Start sale at:</dt>
  <dd><%= @raffle.start_sale_at, format: "%d de %B de %Y" %></dd>

  <dt>Finishes sale at:</dt>
  <dd><%= @raffle.finishes_sale_at %></dd>

  <dt>Drawn at:</dt>
  <dd><%= @raffle.drawn_at%></dd>

  <dt>Ticket value:</dt>
  <dd><%= @raffle.ticket_value %></dd>

  <dt>User:</dt>
  <dd><%= @raffle.user.name %></dd>

  <dt>Kind:</dt>
  <dd><%= @raffle.kind %></dd>

</dl>

app/views/tickets/_form.html.erb
<%= simple_form_for @ticket do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :number %>
    <%= f.association :raffle %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, f.object.new_record? ? 'Create Ticket' : 'Update Ticket', class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<% content_for :title do %>
  Editing Ticket
<% end %>

<div class="page-header">
  <h1>Editing Ticket</h1>
  <div>
    <%= link_to @ticket, class: 'btn btn-info' do %>
      <%= icon 'fas', 'eye' %>
      View
    <% end %>
    <%= link_to tickets_path, class: 'btn btn-outline-secondary' do %>
      <%= icon 'fas', 'bars' %>
      Back
    <% end %>
  </div>
</div>

<%= render 'form' %>

app/views/tickets/index.html.erb
<% content_for :title do %>
  Tickets
<% end %>

<div class="page-header">
  <h1>Tickets</h1>
  <%= link_to new_ticket_path, class: 'btn btn-primary' do %>
    <%= icon 'fas', 'plus' %>
    New Ticket
  <% end %>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Number</th>
        <th>Raffle</th>
        <th>User</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @tickets.each do |ticket| %>
        <tr>
          <td><%= ticket.number %></td>
          <td><%= ticket.raffle.description %></td>
          <td><%= ticket.user.name %></td>
          <td>
            <%= link_to ticket, class: 'btn btn-info btn-sm' do %>
              <%= icon 'fas', 'eye', class: 'fa-fw' %>
            <% end %>
            <%= link_to edit_ticket_path(ticket), class: 'btn btn-success btn-sm' do %>
              <%= icon 'fas', 'edit', class: 'fa-fw' %>
            <% end %>
            <%= link_to ticket, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' do %>
              <%= icon 'fas', 'times', class: 'fa-fw' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tickets/new.html.erb
<% content_for :title do %>
  New Ticket
<% end %>

<div class="page-header">
  <h1>New Ticket</h1>
  <%= link_to tickets_path, class: 'btn btn-outline-secondary' do %>
    <%= icon 'fas', 'bars' %>
    Back
  <% end %>
</div>

<%= render 'form' %>

app/views/tickets/show.html.erb
<% content_for :title do %>
  Ticket's details
<% end %>

<div class="page-header">
  <h1>Ticket's details</h1>
  <div>
    <%= link_to edit_ticket_path(@ticket), class: 'btn btn-success' do %>
      <%= icon 'fas', 'edit' %>
      Edit
    <% end %>
    <%= link_to tickets_path, class: 'btn btn-outline-secondary' do %>
      <%= icon 'fas', 'bars' %>
      Back
    <% end %>
  </div>
</div>

<dl class="dl-horizontal">
  <dt>Number:</dt>
  <dd><%= @ticket.number %></dd>

  <dt>Raffle:</dt>
  <dd><%= @ticket.raffle.title %></dd>

  <dt>User:</dt>
  <dd><%= @ticket.user.name %></dd>

</dl>

app/views/users/edit.html.erb
<% content_for :title do %>
  Editing User
<% end %>

<div class="page-header">
  <h1>Editing User</h1>
  <div>
    <%= link_to @user, class: 'btn btn-info' do %>
      <%= icon 'fas', 'eye' %>
      View
    <% end %>
    <%= link_to users_path, class: 'btn btn-outline-secondary' do %>
      <%= icon 'fas', 'bars' %>
      Back
    <% end %>
  </div>
</div>

<%= render 'form' %>

app/views/users/index.html.erb
<% content_for :title do %>
  Users
<% end %>

<div class="page-header">
  <h1>Users</h1>
  <%= link_to new_user_path, class: 'btn btn-primary' do %>
    <%= icon 'fas', 'plus' %>
    New User
  <% end %>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Password</th>
        <th>Photo</th>
        <th>Root</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.password %></td>
          <td><%= user.photo %></td>
          <td><%= user.root %></td>
          <td>
            <%= link_to user, class: 'btn btn-info btn-sm' do %>
              <%= icon 'fas', 'eye', class: 'fa-fw' %>
            <% end %>
            <%= link_to edit_user_path(user), class: 'btn btn-success btn-sm' do %>
              <%= icon 'fas', 'edit', class: 'fa-fw' %>
            <% end %>
            <%= link_to user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' do %>
              <%= icon 'fas', 'times', class: 'fa-fw' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<% content_for :title do %>
  New User
<% end %>

<div class="page-header">
  <h1>New User</h1>
  <%= link_to users_path, class: 'btn btn-outline-secondary' do %>
    <%= icon 'fas', 'bars' %>
    Back
  <% end %>
</div>

<%= render 'form' %>

app/views/users/show.html.erb
<% content_for :title do %>
  User's details
<% end %>

<div class="page-header">
  <h1>User's details</h1>
  <div>
    <%= link_to edit_user_path(@user), class: 'btn btn-success' do %>
      <%= icon 'fas', 'edit' %>
      Edit
    <% end %>
    <%= link_to users_path, class: 'btn btn-outline-secondary' do %>
      <%= icon 'fas', 'bars' %>
      Back
    <% end %>
  </div>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @user.name %></dd>

  <dt>Email:</dt>
  <dd><%= @user.email %></dd>

  <dt>Password:</dt>
  <dd><%= @user.password %></dd>

  <dt>Photo:</dt>
  <dd><%= @user.photo %></dd>

  <dt>Root:</dt>
  <dd><%= @user.root %></dd>

</dl>